add_train:
  fields:
    entry_id:
      selector:
        text:
    train_id:
      required: true
      selector:
        text:
    name:
      selector:
        text:
    address:
      required: true
      selector:
        number:
          min: 1
          max: 10239
          mode: box
    functions:
      selector:
        object:

update_train:
  fields:
    entry_id:
      selector:
        text:
    train_id:
      required: true
      selector:
        text:
    name:
      selector:
        text:
    address:
      required: true
      selector:
        number:
          min: 1
          max: 10239
          mode: box
    functions:
      selector:
        object:

remove_train:
  fields:
    entry_id:
      selector:
        text:
    train_id:
      required: true
      selector:
        text:

set_power:
  fields:
    entry_id:
      selector:
        text:
    enabled:
      required: true
      selector:
        boolean:
    track:
      selector:
        text:

set_speed:
  target:
    entity:
      integration: railops
      domain: sensor
  fields:
    speed:
      required: true
      selector:
        number:
          min: 0
          max: 126
          step: 1
          mode: slider

set_direction:
  target:
    entity:
      integration: railops
      domain: sensor
  fields:
    forward:
      required: true
      selector:
        boolean:

set_function:
  target:
    entity:
      integration: railops
      domain: sensor
  fields:
    function:
      required: true
      selector:
        text:
    enabled:
      required: true
      selector:
        boolean:

pulse_function:
  target:
    entity:
      integration: railops
      domain: sensor
  fields:
    function:
      required: true
      selector:
        text:
    duration:
      selector:
        number:
          min: 0.05
          max: 10
          step: 0.05
          mode: slider

set_function_mapping:
  target:
    entity:
      integration: railops
      domain: sensor
  fields:
    function_name:
      required: true
      selector:
        text:
    function_number:
      required: true
      selector:
        number:
          min: 0
          max: 28
          step: 1
          mode: box

remove_function_mapping:
  target:
    entity:
      integration: railops
      domain: sensor
  fields:
    function_name:
      required: true
      selector:
        text:

stop:
  target:
    entity:
      integration: railops
      domain: sensor

emergency_stop:
  target:
    entity:
      integration: railops
      domain: sensor
  fields:
    entry_id:
      selector:
        text:
